spring.application.name=GriffonVet
server.servlet.context-path=/api/v1
server.port=8086
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_Veterinaria;encrypt=false
spring.datasource.username=sa
spring.datasource.password=pyxis
spring.datasource.driver-classname=com.microsoft.sqlserver.jdbc.SQLServerDriver
security.jwt.secret=FLORESghinamoMORESCO123456789123!



cloudinary.cloud_name=dqvq8hncc
cloudinary.api_key=334973462227425
cloudinary.api_secret=I-bcdk96kp5sPcCWtHUDpip7gqI